### ISSUE TITLE
Embed Scores on website

### ISSUE THREAD

**Issue by kylemcd** [subscriptionscore/extension#19]
I'd like to be able to show the score of my newsletter on my website before the user subscribes.

**Comment by Jivings** [comment]
Hey Kyle, we'll be opening up our API a little soon, and this sounds like a good application of it. Do you have any thoughts on how you'd like it to look?

**Comment by kylemcd** [comment]
Ideally, the look and feel would be up to the developer. 

Thinking it could just be a GET request where you pass through the URL of your site and it then returns a score.

**Comment by Jivings** [comment]
Instead could it just return whatever site the script was used on? Using the referrer header perhaps?

Just to prevent you from just requesting any site's score and showing that (and to prevent scraping).

**Comment by kylemcd** [comment]
That makes a lot of sense to do it that way. 

There may be some use-case down the road that we're missing that would make sense for this to be passed in instead of the referrer. Guess it's better to cross that bridge when it gets here.
